[versions]
loom = "1.14-SNAPSHOT"
kotlin = "2.2.21"

devauth = "1.2.1"

fabric-loader = "0.17.3"
fabric-language-kotlin = "1.13.7+kotlin.2.2.21"
fabric-api-1-21-8 = "0.136.1+1.21.8"
fabric-api-1-21-10 = "0.138.3+1.21.10"

omnicore = "1.0.0-beta.40"
textile = "1.0.0-beta.8"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

fabric-api-1-21-8 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-1-21-8" }
fabric-api-1-21-10 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-1-21-10" }

omnicore-1-21-8 = { module = "dev.deftu:omnicore-1.21.8-fabric", version.ref = "omnicore" }
omnicore-1-21-10 = { module = "dev.deftu:omnicore-1.21.10-fabric", version.ref = "omnicore" }

textile-1-21-8 = { module = "dev.deftu:textile-1.21.8-fabric", version.ref = "textile" }
textile-1-21-10 = { module = "dev.deftu:textile-1.21.10-fabric", version.ref = "textile" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "loom" }